---
- hosts: all
  become: true

  tasks:
    - name: stop previous version docker
      shell: docker stop calculator-container
    - name: remove stopped container
      shell: docker rm -f calculator-container
    - name: remove docker images
      shell: docker image rm -f saksham1508/calculator:latest
    - name: Pull saksham1508/calculator
      docker_image:
        name: saksham1508/calculator
        source: pull
    - name: create docker image
      shell: docker run -it saksham1508/calculator:latest
