- name: Pull and Run docker image
  hosts: all
  tasks:
    - name: Pull saksham/calculator
      docker_image:
        name: saksham/calculator
        source: pull
      vars:
        - ansible_python_interpreter: /usr/bin/python